RouteScale:
  totalCount:
    v4: 10000
    v6: 0
  Weights: 
    v4: #should be total of 100
      32: 10
      23: 40
      24: 40
      28: 10
    v6: #should be total of 100
      128: 100
  vrfCount: 1
  RoutingProtocol: 'bgp'
  ExcludeIprange:
    v4: '172.16.0.0/12, 10.80.0.0/14' # this is for 172.16.0.0/12
    v6: '' # empty means none
  StartIpPrefix:
    v4: ''
    v6: ''
